<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BabyName;

class MoreBabyNamesSeeder extends Seeder
{
    public function run()
    {
        $names = [
            // Kız İsimleri devam - F-Z harfleri
            ['name' => 'Fatma', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Sütten kesilmiş', 'description' => 'Hz. Fatma\'nın ismi. Saflık ve temizlik simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Feyza', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Bereket, bolluk', 'description' => 'Bereket ve bolluğu temsil eden güzel isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Fulya', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Fulya çiçeği', 'description' => 'Güzel kokulu çiçeği temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Gamze', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Yanakta çukur', 'description' => 'Güzellik ve çekiciliği ifade eden sevimli isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Gizem', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Sır, gizem', 'description' => 'Gizemlilik ve derinliği temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Gül', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Gül çiçeği', 'description' => 'Güzellik ve zarafetin simgesi olan çiçek ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Gülşen', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Gül bahçesi', 'description' => 'Güzellik ve bolluğu temsil eden poetik isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hayal', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Hayal, düş', 'description' => 'Hayal gücü ve yaratıcılığı ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hazal', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Sonbahar yaprağı', 'description' => 'Sonbahar güzelliğini temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hilal', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Hilal, yeni ay', 'description' => 'Yeni başlangıç ve umudun simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İdil', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'İdil nehri, Volga', 'description' => 'Büyük nehri temsil eden coğrafi isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İlayda', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Su perisi', 'description' => 'Efsanevi güzellik ve zarafeti temsil eder.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İnci', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'İnci, sedef', 'description' => 'Değerli ve nadir güzelliği ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İpek', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'İpek kumaş', 'description' => 'Yumuşaklık ve zarafeti temsil eden tekstil ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İrem', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Cennet bahçesi', 'description' => 'Cennet güzelliğini ifade eden dini isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Jale', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Çiy, şebnem', 'description' => 'Saflık ve berraklığı temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kader', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Kader, alın yazısı', 'description' => 'Kader ve yazgıyı ifade eden derin isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kardelen', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Kardelen çiçeği', 'description' => 'İlkbaharın müjdecisi olan çiçek ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kıvılcım', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Kıvılcım, kor', 'description' => 'Enerji ve dinamizmi temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Leman', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Parlaklık, ışık', 'description' => 'Aydınlık ve parlaklığı ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Leyla', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Gece, karanlık güzel', 'description' => 'Gece güzelliğini ifade eden romantik isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Melda', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Genç, taze', 'description' => 'Gençlik ve tazeliği temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Meltem', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Meltem rüzgarı', 'description' => 'Hafif ve serinletici rüzgarı temsil eder.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Meryem', 'gender' => 'kiz', 'origin' => 'İbranice', 'meaning' => 'İsyankâr, asi', 'description' => 'Hz. Meryem\'in ismi. Saflık ve kutsallık simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Mina', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Mine, cam', 'description' => 'Saydamlık ve berraklığı ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Nazlı', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Nazlı, şımarık', 'description' => 'Zarafet ve kadınsı inceliği temsil eder.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Nihan', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Gizli, saklı', 'description' => 'Gizemlilik ve derinliği ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Nisa', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Kadınlar', 'description' => 'Kadınlığı ve feminenliği temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Nurbanu', 'gender' => 'kiz', 'origin' => 'Arapça-Farsça', 'meaning' => 'Nur hanım, ışık hanım', 'description' => 'Aydınlık ve asaleti birleştiren klasik isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Özge', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Özgün, farklı', 'description' => 'Özgünlük ve farklılığı temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Özlem', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Özlem, hasret', 'description' => 'Derin duyguları ifade eden duygusal isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Pelin', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Pelin otu', 'description' => 'Şifalı bitkiyi temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Pınar', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Pınar, kaynak', 'description' => 'Temiz su kaynağını temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Rabia', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'İlkbahar, dördüncü', 'description' => 'Yenilenme ve güzellik mevsimini temsil eder.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Rüya', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Rüya, düş', 'description' => 'Hayal gücü ve umutları ifade eden poetik isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Seda', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Ses, seda', 'description' => 'Güzel ses ve melodiyi temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Seher', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Şafak, tan', 'description' => 'Yeni günün başlangıcını ifade eden umut ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Sevgi', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Sevgi, aşk', 'description' => 'Sevgi ve şefkati temsil eden duygusal isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Simge', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Simge, sembol', 'description' => 'Anlam ve değeri temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Şebnem', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'Çiy, şebnem', 'description' => 'Saflık ve berraklığı temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Şeyma', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Güzel yüzlü', 'description' => 'Hz. Muhammed\'in süt kardeşi. Güzellik simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Tuba', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Cennet ağacı', 'description' => 'Cennet güzelliğini ifade eden dini isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Tuğba', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Tuğ, bayrak', 'description' => 'Zafer ve gururun simgesi olan isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ülkü', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'İdeal, ülkü', 'description' => 'Yüksek idealleri temsil eden değerli isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ümit', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Umut, ümit', 'description' => 'Umut ve iyimserliği ifade eden pozitif isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Vildan', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Cennet kızı', 'description' => 'Cennet güzelliğini ifade eden dini isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Yağmur', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Yağmur', 'description' => 'Bereket ve yenilemeyi temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Yelda', 'gender' => 'kiz', 'origin' => 'Farsça', 'meaning' => 'En uzun gece', 'description' => 'Kış gündönümünü ifade eden özel isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Yeliz', 'gender' => 'kiz', 'origin' => 'Türkçe', 'meaning' => 'Yeşil iz', 'description' => 'Doğa ve yeşilliği temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Zehra', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Parlak, aydınlık', 'description' => 'Hz. Fatma\'nın lakabı. Parlaklık simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Zeliha', 'gender' => 'kiz', 'origin' => 'Arapça', 'meaning' => 'Güzel saçlı', 'description' => 'Hz. Yusuf\'un hikayesindeki güzel kadın.', 'popularity_rank' => null, 'is_popular' => false],

            // Erkek İsimleri devam - C-Z harfleri
            ['name' => 'Can', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Can, ruh', 'description' => 'Yaşam ve canlılığı temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Caner', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Can er, canlı erkek', 'description' => 'Canlılık ve erkekliği birleştiren isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Cihan', 'gender' => 'erkek', 'origin' => 'Farsça', 'meaning' => 'Dünya, cihan', 'description' => 'Büyüklük ve evrenselliği temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Çağan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Çağ, zaman', 'description' => 'Zamanı ve çağı temsil eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Çağlar', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Çağlar, zamanlar', 'description' => 'Sonsuzluk ve zamanı ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Çetin', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Sert, dayanıklı', 'description' => 'Dayanıklılık ve sertliği temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Deniz', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Deniz', 'description' => 'Sonsuzluk ve özgürlüğü temsil eden unisex isim.', 'popularity_rank' => null, 'is_popular' => true],
            ['name' => 'Doğan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Doğan, şahin', 'description' => 'Güç ve keskin zekayı temsil eden hayvan ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Doruk', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Zirve, doruk', 'description' => 'Yükseklik ve başarıyı temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ege', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Ege denizi', 'description' => 'Ege bölgesinin güzelliğini temsil eden unisex isim.', 'popularity_rank' => null, 'is_popular' => true],
            ['name' => 'Emre', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Kardeş, dost', 'description' => 'Dostluk ve kardeşliği temsil eden sevimli isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Engin', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Engin, geniş', 'description' => 'Genişlik ve büyüklüğü ifade eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Erdem', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Erdem, fazilet', 'description' => 'Ahlaki değerleri temsil eden değerli isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Erhan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Er han, erkek hükümdar', 'description' => 'Liderlik ve erkekliği birleştiren güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Erkan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Er kan, erkek kanı', 'description' => 'Erkeklik ve güçlü soyluluğu temsil eder.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ertuğrul', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Er tuğrul, erkek şahin', 'description' => 'Osmanlı tarihinden güçlü liderlik ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Fatih', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Fethedici, galip', 'description' => 'Fatih Sultan Mehmet\'in ismi. Zafer simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Furkan', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Hak ile batılı ayıran', 'description' => 'Kur\'an\'ın isimlerinden. Adalet simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Gökhan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Gök han, göğün hükümdarı', 'description' => 'Yücelik ve liderliği birleştiren güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Güney', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Güney yön', 'description' => 'Sıcaklık ve aydınlığı temsil eden yön ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hakan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Hakan, hükümdar', 'description' => 'Türk tarihinde hükümdar unvanı. Liderlik simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Halil', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Dost, arkadaş', 'description' => 'Hz. İbrahim\'in lakabı. Dostluk simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hamza', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Aslan, güçlü', 'description' => 'Hz. Hamza\'nın ismi. Güç ve cesaret simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hasan', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Güzel, iyi', 'description' => 'Hz. Hasan\'ın ismi. Güzellik ve iyilik simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Hüseyin', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Güzel, yakışıklı', 'description' => 'Hz. Hüseyin\'in ismi. Güzellik ve fedakarlık simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İbrahim', 'gender' => 'erkek', 'origin' => 'İbranice', 'meaning' => 'Çok babası olan', 'description' => 'Hz. İbrahim\'in ismi. Babalık ve liderlik simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İlhan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'İl han, bölge hükümdarı', 'description' => 'Yöneticilik ve liderliği temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'İsmail', 'gender' => 'erkek', 'origin' => 'İbranice', 'meaning' => 'Allah işitir', 'description' => 'Hz. İsmail\'in ismi. Sabır ve fedakarlık simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kağan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Kağan, büyük han', 'description' => 'Türk tarihinde en yüksek hükümdar unvanı.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kadir', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Güçlü, kudretli', 'description' => 'Güç ve kudreti temsil eden dini isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Kaya', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Kaya, taş', 'description' => 'Sağlamlık ve dayanıklılığı temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Koray', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Kor ay, ateşli ay', 'description' => 'Ateş ve ay\'ın gücünü birleştiren poetik isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Levent', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Genç asker, levent', 'description' => 'Gençlik ve askerliği temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Mehmet', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Övülen, methiye layık', 'description' => 'Hz. Muhammed\'in Türkçe formu. En yaygın erkek ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Murat', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'İstek, arzu', 'description' => 'Osmanlı padişah ismi. Arzu ve hedef simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Oğuz', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Oğuz, Türk boyu', 'description' => 'Türk tarihinden güçlü boy ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Onur', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Onur, şeref', 'description' => 'Şeref ve gururun simgesi olan değerli isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ozan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Ozan, şair', 'description' => 'Şiir ve sanatı temsil eden yaratıcı isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Özcan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Öz can, gerçek can', 'description' => 'Özgünlük ve canlılığı birleştiren isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Polat', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Çelik, sert metal', 'description' => 'Sertlik ve dayanıklılığı temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Recep', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Saygı gören ay', 'description' => 'İslami takvimde kutsal ay ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Selim', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Sağlam, güvenli', 'description' => 'Güvenlik ve sağlamlığı temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Serkan', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Ser kan, baş kan', 'description' => 'Liderlik ve soyluluk ifade eden modern isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Sinan', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Mızrak ucu', 'description' => 'Mimar Sinan\'ın ismi. Keskinlik ve ustalık simgesi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Taner', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Tan er, şafak erkeği', 'description' => 'Yeni başlangıç ve erkekliği birleştiren isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Tolga', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Savaş miğferi', 'description' => 'Koruma ve savaşçılığı temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Tunç', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Tunç metal', 'description' => 'Sertlik ve değerli metali temsil eden isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Uğur', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Uğur, şans', 'description' => 'İyi şans ve bereket simgesi olan pozitif isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Ümit', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Umut, ümit', 'description' => 'Umut ve iyimserliği temsil eden pozitif isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Volkan', 'gender' => 'erkek', 'origin' => 'Latince', 'meaning' => 'Yanardağ', 'description' => 'Güç ve enerjiyi temsil eden doğa ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Yasin', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Kur\'an suresi', 'description' => 'Kur\'an\'ın kalbi sayılan sure ismi.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Yiğit', 'gender' => 'erkek', 'origin' => 'Türkçe', 'meaning' => 'Cesur, yiğit', 'description' => 'Cesaret ve kahramanlığı temsil eden güçlü isim.', 'popularity_rank' => null, 'is_popular' => false],
            ['name' => 'Zafer', 'gender' => 'erkek', 'origin' => 'Arapça', 'meaning' => 'Zafer, galibiyet', 'description' => 'Başarı ve zaferi temsil eden motivasyonel isim.', 'popularity_rank' => null, 'is_popular' => false]
        ];

        foreach ($names as $name) {
            BabyName::create($name);
        }
    }
}